# Generated by Django 5.1.2 on 2024-10-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='surname',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
